### ISSUE TITLE
Unattended Upgrades with the latest security updates

### ISSUE THREAD

**Issue by cmonty14** [steadfasterX/arch_uau#2]
Hi,
I understand the explanation of Arch upgrade philosophy.
However one could consider Unattended Upgrades with the latest security updates.
What do you think?

Debian is providing this [functionality](https://wiki.debian.org/UnattendedUpgrades).

**Comment by steadfasterX** [comment]
well no.. that will not work for Arch.
everything depends on everything. updating just a part of the system will 100% lead to damage one day.
and before you ask: that will never change as rolling releases work that way..
